apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsc-vite-ts-app
  namespace: jsc-ns
  labels:
    app: jsc-vite-ts-app
    component: jsc-vite-ts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsc-vite-ts-app
      tier: frontend
  template:
    metadata:
      labels:
        app: jsc-vite-ts-app
        tier: frontend
    spec:
      containers:
        - name: jsc-vite-ts
          image: jscdroiddev/jsc-vite-ts:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Asia/Bangkok"
          ports:
            - containerPort: 80
              name: jsc-vite-ts-app
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "128Mi"
